### PR TITLE
Disable animation for attributes

### PR DESCRIPTION
**Pull request by steflyx**
**Please check the type of change your PR introduces:**
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring / Code style update (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation
- [ ] Other (please describe): 

 - Introduced prop "DisableAnimationForAttributes" which takes an array of strings (default value empty array), each indicating the name of an attribute which shouldn't be animated.

Ex.

`<AnimatedDataset
          dataset={dataset}
          tag="rect"
          attrs={{
            fill: (d) => (hoveredElement === d.index ? "red" : "blue"),
            height: (d) => d.value * 10,
            x: (_, i) => (i + 1) * 100,
            width: 50,
            y: (d) => 500 - d.value * 10,
          }}
          duration={1000}
          events={{
            onMouseEnter: (MouseEvent, d) => setHoveredElement(d.index),
            onMouseleave: (MouseEvent) => setHoveredElement(null),
          }}
          disableAnimationForAttributes={["fill"]}
          keyFn={(d) => d.index}
        />`

Without the line `disableAnimationForAttributes={["fill"]}`, if you hover on the bars, the color will take 1s to change gradually from blue to red. 
When you add the line, the effect on the color will be immediate, while the y and height attributes will still be animated

- Added packages jest, jest-config-accurapp and @babel/preset-env in order to run tests locally

### CODE REVIEW

**Comment by ivanross** [comment]
@steflyx maybe instead of `disableAnimationForAttributes` we could have a a prop to customize animation duration separately. So you could set a duration of 0 to "disable" the animation. Also, this would be useful for @filippoelgorni's proposal #20. 

What do you think?
cc @caesarsol

**Comment by steflyx** [comment]
> @steflyx maybe instead of `disableAnimationForAttributes` we could have a a prop to customize animation duration separately. So you could set a duration of 0 to "disable" the animation. Also, this would be useful for @filippoelgorni's proposal #20.
> 
> What do you think? cc @caesarsol

**Comment by steflyx** [comment]
> @steflyx maybe instead of `disableAnimationForAttributes` we could have a a prop to customize animation duration separately. So you could set a duration of 0 to "disable" the animation. Also, this would be useful for @filippoelgorni's proposal #20.
> 
> What do you think? cc @caesarsol

Actually that was my idea in the beginning but turns out it's not so easy to have animations with different durations on different attributes. There's a workaround that I found [here](https://stackoverflow.com/questions/64392917/how-to-transition-two-properties-with-different-durations) but I have to check if it works. I can give it a try!

**Comment by steflyx** [comment]
I managed! Now you can insert a custom duration, delay or easing by attribute (and since you can disable the animation by inserting duration=0, I removed the prop disableAnimationForSingleAttributes that I inserted initially)

cc @caesarsol

**Comment by ivanross** [comment]
@steflyx great!! 💣

I would use a simpler name for the attributes, something like `durationByAttr` etc.

Also can you please mention the new props in the README??

thank you 🙏

**Comment by steflyx** [comment]
Done both!

**Review by ivanross — APPROVED** [review]

**Comment by caesarsol** [comment]
great job guys ;)

**Pull request merged**
